### ISSUE TITLE
全局 CONFIG 耦合程度过高，建议恢复传参形式

### ISSUE THREAD

**Issue by ymzhang-cs** [ymzhang-cs/BJTU-Homework-Tracker#36]
RT

@hewkick @ram6ert

**Comment by ram6ert** [comment]
具体怎么传，之前设想可以让每个模块注册自己的配置的

**Comment by ymzhang-cs** [comment]
我觉得可以传 `dict`。

比如在下面的 config 里，可以直接把 `login` 的键值对传入 Login 对象。Login 对象里面再根据 active 的方法进行相应的传参。

```yaml
# Step 1: Login
login:
  active: cp
  mis:
    webdriver_path: ""
    browser: edge
  cookie:
    JSESSIONID: ""
  cp:
    student_id: "23114514"
    password: "pass:Bjtu@23114514"
```
